### ISSUE TITLE
404 Error for Task Switching at Batter Tasks Link

### ISSUE THREAD

**Issue by mvoloshi** [thartbm/SMCL-online#1]
"try it here" link under Task Switching at https://thartbm.github.io/SMCL-online/ leads to 404 error shown below.

![image](https://user-images.githubusercontent.com/85046461/120090916-303f8100-c0d4-11eb-992c-545e35b905c7.png)

**Comment by thartbm** [comment]
Thanks! Finally saw this and fixed it...

**Comment by thartbm** [comment]
Closed.
